name: Coverage Test
on: 
  pull_request: 
    branches:
    - main

jobs:
  coverage:
    run-on: ubuntu-latest

    steps: 
    -name: Checkout Repository
    uses: actions/checkout@v4

    -name: Setup Python
    use: setup-python@v5
    with:
      python-version: '3.x'

    -name: Install Dependencies
    use: pip install -r requirements.txt

    -name: Run Test With Coverages
    use: pytest --cov=src --cov-report=term-mising --cov-fail-under=85